#ifndef __NOS_EVENT_TYPES_H__
#define __NOS_EVENT_TYPES_H__

namespace nos::firewall {

enum event_type {
    NO_ERROR,
    ETH_DESERIALIZE_FAILED,
    ARP_DESERIALIZE_FAILED,
    ARP_INVAL_ARP_OPERATION,
    ARP_HEADER_LEN_TOO_SHORT,
    ARP_HWADDR_LEN_INVAL,
    IPV4_VERSION_INVAL,
    IPV4_IHL_INVAL,
    IPV4_RESERVED_FLAG_SET,
    IPV4_DONT_FRAGMENT_SET,
    IPV4_MORE_FRAGMENT_SET,
    IPV4_MF_DF_FLAGS_SET,
    IPV6_VERSION_INVAL,
    UDP_SRC_PORT_IS_ZERO,
    UDP_DEST_PORT_IS_ZERO,
    ICMP6_TYPE_UNSUPPORTED,
    ICMP6_TYPE_UNSUPPORTED_OPTION,
    MACSEC_INVAL_VERSION,
    MACSEC_INVAL_SCI_SCB,
    MACSEC_INVAL_C,
    UNSUPPORTED_ETHERTYPE,
    UNSUPPORTED_PROTOCOL,
    PACKET_LEN_TOO_SHORT,
};

}

#endif
