#ifndef __ERROR_TYPES_H__
#define __ERROR_TYPES_H__

enum aos_error {
    AOS_CRYPTO_ERROR_HASH_INVALID,
    AOS_CRYPTO_ERROR_OPENSSL_EVP_HASH_UPDATE_FAIL,
    AOS_CRYPTO_ERROR_OPENSSL_EVP_HASH_GEN_FAIL,
    AOS_CRYPTO_ERROR_HASH_INVALID_INPUT,
};

#endif
